# Generated by Django 5.0 on 2024-08-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='role',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM.account'),
        ),
    ]
