# Generated by Django 5.0 on 2024-08-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_role_delete_user_alter_account_money_role_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name_role',
            new_name='role_name',
        ),
    ]
