# Generated by Django 5.0 on 2024-08-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0003_rename_name_role_role_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ATM.role'),
        ),
    ]
