# Generated by Django 5.0 on 2024-08-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0005_remove_account_role_role_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='role',
        ),
    ]
