# Generated by Django 5.0 on 2024-08-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0007_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ATM.client'),
        ),
    ]
